// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkyAPI.Data;

namespace ParkyAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201124143612_SeedingNationalParkData")]
    partial class SeedingNationalParkData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParkyAPI.Models.NationalPark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Established")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NationalParks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2020, 11, 24, 18, 6, 11, 619, DateTimeKind.Local).AddTicks(4112),
                            Established = new DateTime(2020, 11, 24, 18, 6, 11, 624, DateTimeKind.Local).AddTicks(6164),
                            Name = "NP",
                            State = "IL"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2020, 11, 24, 18, 6, 11, 624, DateTimeKind.Local).AddTicks(7083),
                            Established = new DateTime(2020, 11, 24, 18, 6, 11, 624, DateTimeKind.Local).AddTicks(7122),
                            Name = "NPTest",
                            State = "TS"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
